name: Build package

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

concurrency: build-${{ github.ref }}

env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      image-archive: image.tar
      image-repository: ${{ steps.prepare-repository-name.outputs.repository }}
      image-tag: ${{ steps.extract-metadata.outputs.version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare repository name
      id: prepare-repository-name
      run: |
        repository=$REGISTRY/${{ github.repository }}
        echo "repository=${repository,,}" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: extract-metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.prepare-repository-name.outputs.repository }}

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        cache-from: |
          type=gha,scope=sha-${{ github.sha }}
          type=gha,scope=${{ github.ref_name }}
          type=gha,scope=${{ github.base_ref || 'main' }}
          type=gha,scope=main
        cache-to: |
          type=gha,scope=sha-${{ github.sha }},mode=max
          type=gha,scope=${{ github.ref_name }},mode=max
        outputs: |
          type=oci,dest=${{ runner.temp }}/image.tar
        tags: ${{ steps.extract-metadata.outputs.tags }}
        labels: ${{ steps.extract-metadata.outputs.labels }}
